### ISSUE TITLE
race condition with loader when multiple charts on the same page

### ISSUE THREAD

**Issue by duanefields** [rakannimer/react-google-charts#197]
If I have two charts on the same page, in different components, I get an error loading the second one, which doesn't appear.

Google Charts loader.js can only be loaded once

I'm assuming this is a race condition where they both start loading, then the second one bombs because the first one wins. Is there a general strategy for avoiding this issue?

**Comment by duanefields** [comment]
It looks like isLoading never gets set to true, so it just tries to load the script again.

**Comment by oehm-smith** [comment]
Dupe of #195

**Comment by duanefields** [comment]
Fixed by https://github.com/rakannimer/react-google-charts/pull/199

**Comment by FabianSchuessler** [comment]
This issue was only fixed for multiple charts on one page.
The issue still persists for charts on different pages.
