### ISSUE TITLE
Pie Chart flicker when mouse hover 

### ISSUE THREAD

**Issue by minaairsupport** [rakannimer/react-google-charts#302]
I have a big issue with your nice pic chart that when I hover with the mouse it keep flashing with tooltip 

here is a sample of my code 

nothing fancy in my code but I need this issue to be fixed as soon as possible 

https://codesandbox.io/s/confident-currying-e21sg

**Comment by crichmond1989** [comment]
This flicker behavior is showing up on the documentation example (https://react-google-charts.com/pie-chart).

**Comment by crichmond1989** [comment]
Hmm, looks like this is an issue with the Google Charts library. The Google Charts documentation has the same behavior: https://developers.google.com/chart/interactive/docs/gallery/piechart

**Comment by lksilva** [comment]
if you set` tooltip: { isHtml: true }` and define  css to `pointer-events: none;` in wrapper that contains this problem is solved. 

There is a way to implements custom tooltip, or overrrid className? `google-visualization-tooltip`

**Comment by punith-bm** [comment]
@lksilva  we've tried in the same way as you mentioned. But still facing the flickering effect. Can you please help us out with some example sample or so?

**Comment by gujral1997** [comment]
This flicker issue is in the main library as well. And this library is just a wrapper. In my opinion, this is not the right place to ask this question as the issue is not with this wrapper.

**Comment by nimesha95** [comment]
I did fixed this issue by adding below css 

`svg > g > g:last-child { pointer-events: none }`

[https://stackoverflow.com/questions/37902708/google-charts-tooltip-flickering](url)
[https://github.com/google/google-visualization-issues/issues/2162](url)
